Repository kubernetes-sigs/tejolote, pull requests merged in 2022-11, with the labels that each got.

#2 Add SIG Release Issue Tempaltes
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#4 add cloudbuild to build binaries and image
  cloudbuild.yaml
  magefile.go
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/M

#5 increase timeout and machinetype
  cloudbuild.yaml
Labels: cncf-cla: yes, approved, lgtm, kind/cleanup, size/XS

#6 Add version command and update some dependencies
  go.mod
  go.sum
  internal/cmd/main.go
  magefile.go
  scripts/verify-build.sh
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/M

#7 Dependabot
  .github/SECURITY.md
  .github/dependabot.yml
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/M

#12 Prewarm sigstore TUF cache before signing
  pkg/attestation/sign.go
Labels: kind/bug, cncf-cla: yes, approved, lgtm, size/M
